In [3]:
#sqewrthyjuki
print("hi ")

hi

In [4]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv("nba.csv")
print(df.head())

            Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0

             College     Salary
0              Texas  7730337.0
1          Marquette  6796117.0
2  Boston University        NaN
3      Georgia State  1148640.0
4                NaN  5000000.0

In [6]:
print(pd.options.display.max_rows)

60

In [7]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    str
 1   Team      457 non-null    str
 2   Number    457 non-null    float64
 3   Position  457 non-null    str
 4   Age       457 non-null    float64
 5   Height    457 non-null    str
 6   Weight    457 non-null    float64
 7   College   373 non-null    str
 8   Salary    446 non-null    float64
dtypes: float64(4), str(5)
memory usage: 32.3 KB
None

In [11]:
new_df=df.dropna()
#print(new_df)

print(new_df.info())

<class 'pandas.DataFrame'>
Index: 364 entries, 0 to 456
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      364 non-null    str
 1   Team      364 non-null    str
 2   Number    364 non-null    float64
 3   Position  364 non-null    str
 4   Age       364 non-null    float64
 5   Height    364 non-null    str
 6   Weight    364 non-null    float64
 7   College   364 non-null    str
 8   Salary    364 non-null    float64
dtypes: float64(4), str(5)
memory usage: 28.4 KB
None

In [12]:
print(df.aggregate({"Number":["min","max","mean"],
                    "Salary":["min","max","mean"],
                    "Age":["min","mean"]}))

         Number        Salary        Age
min    0.000000  3.088800e+04  19.000000
max   99.000000  2.500000e+07        NaN
mean  17.678337  4.842684e+06  26.938731

In [16]:
print(df.mean(numeric_only=True, axis=0))

Number    1.767834e+01
Age       2.693873e+01
Weight    2.215230e+02
Salary    4.842684e+06
dtype: float64

In [19]:
df['try_column']=1
print(df.head())

            Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0

             College     Salary  try_column
0              Texas  7730337.0           1
1          Marquette  6796117.0           1
2  Boston University        NaN           1
3      Georgia State  1148640.0           1
4                NaN  5000000.0           1

In [26]:
df=pd.read_csv("nba.csv",index_col="Name")
print(df.head())

df.drop(["Avery Bradley"],inplace=True)
print(df.head())

                         Team  Number Position   Age Height  Weight  \
Name
Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
Jae Crowder    Boston Celtics    99.0       SF  25.0    6-6   235.0
John Holland   Boston Celtics    30.0       SG  27.0    6-5   205.0
R.J. Hunter    Boston Celtics    28.0       SG  22.0    6-5   185.0
Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0

                         College     Salary
Name
Avery Bradley              Texas  7730337.0
Jae Crowder            Marquette  6796117.0
John Holland   Boston University        NaN
R.J. Hunter        Georgia State  1148640.0
Jonas Jerebko                NaN  5000000.0
                         Team  Number Position   Age Height  Weight  \
Name
Jae Crowder    Boston Celtics    99.0       SF  25.0    6-6   235.0
John Holland   Boston Celtics    30.0       SG  27.0    6-5   205.0
R.J. Hunter    Boston Celtics    28.0       SG  22.0    6-5   185.0
Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
Amir Johnson   Boston Celtics    90.0       PF  29.0    6-9   240.0

                         College      Salary
Name
Jae Crowder            Marquette   6796117.0
John Holland   Boston University         NaN
R.J. Hunter        Georgia State   1148640.0
Jonas Jerebko                NaN   5000000.0
Amir Johnson                 NaN  12000000.0

In [30]:
df["try_column"]=1
print(df.head())    

df.drop("try_column",axis=1,inplace=True)
print(df.head())

                         Team  Number Position   Age Height  Weight  \
Name
Jae Crowder    Boston Celtics    99.0       SF  25.0    6-6   235.0
John Holland   Boston Celtics    30.0       SG  27.0    6-5   205.0
R.J. Hunter    Boston Celtics    28.0       SG  22.0    6-5   185.0
Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
Amir Johnson   Boston Celtics    90.0       PF  29.0    6-9   240.0

                         College      Salary  try_column
Name
Jae Crowder            Marquette   6796117.0           1
John Holland   Boston University         NaN           1
R.J. Hunter        Georgia State   1148640.0           1
Jonas Jerebko                NaN   5000000.0           1
Amir Johnson                 NaN  12000000.0           1
                         Team  Number Position   Age Height  Weight  \
Name
Jae Crowder    Boston Celtics    99.0       SF  25.0    6-6   235.0
John Holland   Boston Celtics    30.0       SG  27.0    6-5   205.0
R.J. Hunter    Boston Celtics    28.0       SG  22.0    6-5   185.0
Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
Amir Johnson   Boston Celtics    90.0       PF  29.0    6-9   240.0

                         College      Salary
Name
Jae Crowder            Marquette   6796117.0
John Holland   Boston University         NaN
R.J. Hunter        Georgia State   1148640.0
Jonas Jerebko                NaN   5000000.0
Amir Johnson                 NaN  12000000.0

In [33]:

df = pd.DataFrame({"A":[12, 4, 5, None, 1], 
                   "B":[7, 2, 54, 3, None], 
                   "C":[20, 16, 11, 3, 8], 
                   "D":[14, 3, None, 2, 6]}) 

index_ = ['Row_1', 'Row_2', 'Row_3', 'Row_4', 'Row_5']

df.index = index_

print(df)

result = df.truncate(before = 'Row_3', after = 'Row_4')
print(result)

          A     B   C     D
Row_1  12.0   7.0  20  14.0
Row_2   4.0   2.0  16   3.0
Row_3   5.0  54.0  11   NaN
Row_4   NaN   3.0   3   2.0
Row_5   1.0   NaN   8   6.0
         A     B   C    D
Row_3  5.0  54.0  11  NaN
Row_4  NaN   3.0   3  2.0

In [39]:
display(df.head())
df.sort_values("A",ascending=True,inplace=True)
display(df.head())

          A     B   C     D
Row_1  12.0   7.0  20  14.0
Row_3   5.0  54.0  11   NaN
Row_2   4.0   2.0  16   3.0
Row_5   1.0   NaN   8   6.0
Row_4   NaN   3.0   3   2.0

          A     B   C     D
Row_5   1.0   NaN   8   6.0
Row_2   4.0   2.0  16   3.0
Row_3   5.0  54.0  11   NaN
Row_1  12.0   7.0  20  14.0
Row_4   NaN   3.0   3   2.0

In [46]:
df_csv=pd.read_csv("nba.csv")
print(df_csv.head())
print("\n\n")
print(df_csv.groupby('Name').groups)
print("\n\n ")
print(df_csv.groupby('Team').groups)

gk=df_csv.groupby("Name")
gk.first()

            Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0

             College     Salary
0              Texas  7730337.0
1          Marquette  6796117.0
2  Boston University        NaN
3      Georgia State  1148640.0
4                NaN  5000000.0



{'Aaron Brooks': [152], 'Aaron Gordon': [356], 'Aaron Harrison': [328], 'Adreian Payne': [404], 'Al Horford': [312], 'Al Jefferson': [330], 'Al-Farouq Aminu': [428], 'Alan Anderson': [368], 'Alan Williams': [135], 'Alec Burks': [444], 'Alex Len': [128], 'Alex Stepheson': [273], 'Alexis Ajinca': [275], 'Allen Crabbe': [430], 'Alonzo Gee': [287], 'Amar'e Stoudemire': [348], 'Amir Johnson': [5], 'Anderson Varejao': [90], 'Andre Drummond': [188], 'Andre Iguodala': [83], 'Andre Miller': [304], 'Andre Roberson': [423], 'Andrew Bogut': [78], 'Andrew Goudelock': [248], 'Andrew Nicholson': [362], 'Andrew Wiggins': [411], 'Anthony Brown': [108], 'Anthony Davis': [281], 'Anthony Morrow': [421], 'Anthony Tolliver': [195], 'Archie Goodwin': [125], 'Aron Baynes': [182], 'Arron Afflalo': [30], 'Austin Rivers': [104], 'Avery Bradley': [0], 'Axel Toupane': [397], 'Ben McLemore': [148], 'Bismack Biyombo': [61], 'Blake Griffin': [96], 'Boban Marjanovic': [302], 'Bobby Portis': [163], 'Bojan Bogdanovic': [15], 'Boris Diaw': [297], 'Bradley Beal': [369], 'Brandan Wright': [274], 'Branden Dawson': [94], 'Brandon Bass': [106], 'Brandon Jennings': [359], 'Brandon Knight': [127], 'Brandon Rush': [87], 'Brian Roberts': [440], 'Briante Weber': [350], 'Brook Lopez': [23], 'Bruno Caboclo': [62], 'Bryce Cotton': [263], 'Bryce Dejean-Jones': [282], 'C.J. McCollum': [437], 'C.J. Miles': [205], 'C.J. Watson': [367], 'C.J. Wilcox': [105], 'Cameron Bairstow': [151], 'Cameron Payne': [422], 'Carl Landry': [52], 'Carmelo Anthony': [33], 'Caron Butler': [139], 'Chandler Parsons': [238], 'Channing Frye': [167], 'Charlie Villanueva': [240], 'Chase Budinger': [123], 'Chris Andersen': [259], 'Chris Bosh': [339], 'Chris Johnson': [451], 'Chris Kaman': [434], 'Chris McCullough': [24], 'Chris Paul': [100], 'Christian Wood': [60], 'Cleanthony Early': [35], 'Cliff Alexander': [427], 'Clint Capela': [246], 'Cody Zeller': [338], 'Cole Aldrich': [91], 'Corey Brewer': [245], 'Cory Joseph': [66], 'Courtney Lee': [334], 'Cristiano Felicio': [155], 'D'Angelo Russell': [116], 'D.J. Augustin': [384], 'Dahntay Jones': [171], 'Damian Lillard': [436], 'Damien Inglis': [217], 'Damjan Rudez': [408], 'Danilo Gallinari': [388], 'Danny Green': [300], 'Dante Cunningham': [280], 'Dante Exum': [445], 'Darrell Arthur': [383], 'Darren Collison': [142], 'Darrun Hilliard': [190], 'David Lee': [232], 'David West': [308], ...}



{'Atlanta Hawks': [309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323], 'Boston Celtics': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14], 'Brooklyn Nets': [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], 'Charlotte Hornets': [324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338], 'Chicago Bulls': [151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165], 'Cleveland Cavaliers': [166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180], 'Dallas Mavericks': [227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241], 'Denver Nuggets': [383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397], 'Detroit Pistons': [181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195], 'Golden State Warriors': [76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90], 'Houston Rockets': [242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256], 'Indiana Pacers': [196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210], 'Los Angeles Clippers': [91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105], 'Los Angeles Lakers': [106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120], 'Memphis Grizzlies': [257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274], 'Miami Heat': [339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353], 'Milwaukee Bucks': [211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226], 'Minnesota Timberwolves': [398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411], 'New Orleans Pelicans': [275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293], 'New York Knicks': [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45], 'Oklahoma City Thunder': [412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426], 'Orlando Magic': [354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367], 'Philadelphia 76ers': [46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60], 'Phoenix Suns': [121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135], 'Portland Trail Blazers': [427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441], 'Sacramento Kings': [136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150], 'San Antonio Spurs': [294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308], 'Toronto Raptors': [61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75], 'Utah Jazz': [442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456], 'Washington Wizards': [368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382]}

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Aaron Brooks,Chicago Bulls,0.0,PG,31.0,6-0,161.0,Oregon,2250000.0
Aaron Gordon,Orlando Magic,0.0,PF,20.0,6-9,220.0,Arizona,4171680.0
Aaron Harrison,Charlotte Hornets,9.0,SG,21.0,6-6,210.0,Kentucky,525093.0
Adreian Payne,Minnesota Timberwolves,33.0,PF,25.0,6-10,237.0,Michigan State,1938840.0
Al Horford,Atlanta Hawks,15.0,C,30.0,6-10,245.0,Florida,12000000.0
...,...,...,...,...,...,...,...,...
Wilson Chandler,Denver Nuggets,21.0,SF,29.0,6-8,225.0,DePaul,10449438.0
Xavier Munford,Memphis Grizzlies,14.0,PG,24.0,6-3,180.0,Rhode Island,NaN
Zach LaVine,Minnesota Timberwolves,8.0,PG,21.0,6-5,189.0,UCLA,2148360.0
Zach Randolph,Memphis Grizzlies,50.0,PF,34.0,6-9,260.0,Michigan State,9638555.0
Zaza Pachulia,Dallas Mavericks,27.0,C,32.0,6-11,275.0,NaN,5200000.0

In [54]:
df_csv.groupby(['Name',"Age"]).sum()

,,Team,Number,Position,Height,Weight,College,Salary
Name,Age,,,,,,,
Aaron Brooks,31.0,Chicago Bulls,0.0,PG,6-0,161.0,Oregon,2250000.0
Aaron Gordon,20.0,Orlando Magic,0.0,PF,6-9,220.0,Arizona,4171680.0
Aaron Harrison,21.0,Charlotte Hornets,9.0,SG,6-6,210.0,Kentucky,525093.0
Adreian Payne,25.0,Minnesota Timberwolves,33.0,PF,6-10,237.0,Michigan State,1938840.0
Al Horford,30.0,Atlanta Hawks,15.0,C,6-10,245.0,Florida,12000000.0
...,...,...,...,...,...,...,...,...
Wilson Chandler,29.0,Denver Nuggets,21.0,SF,6-8,225.0,DePaul,10449438.0
Xavier Munford,24.0,Memphis Grizzlies,14.0,PG,6-3,180.0,Rhode Island,0.0
Zach LaVine,21.0,Minnesota Timberwolves,8.0,PG,6-5,189.0,UCLA,2148360.0
Zach Randolph,34.0,Memphis Grizzlies,50.0,PF,6-9,260.0,Michigan State,9638555.0
Zaza Pachulia,32.0,Dallas Mavericks,27.0,C,6-11,275.0,,5200000.0

In [56]:
grp = df_csv.groupby('Name')
for name, group in grp:
    print(name)
    print(group)
    print()

Aaron Brooks
             Name           Team  Number Position   Age Height  Weight  \
152  Aaron Brooks  Chicago Bulls     0.0       PG  31.0    6-0   161.0

    College     Salary
152  Oregon  2250000.0

Aaron Gordon
             Name           Team  Number Position   Age Height  Weight  \
356  Aaron Gordon  Orlando Magic     0.0       PF  20.0    6-9   220.0

     College     Salary
356  Arizona  4171680.0

Aaron Harrison
               Name               Team  Number Position   Age Height  Weight  \
328  Aaron Harrison  Charlotte Hornets     9.0       SG  21.0    6-6   210.0

      College    Salary
328  Kentucky  525093.0

Adreian Payne
              Name                    Team  Number Position   Age Height  \
404  Adreian Payne  Minnesota Timberwolves    33.0       PF  25.0   6-10

     Weight         College     Salary
404   237.0  Michigan State  1938840.0

Al Horford
           Name           Team  Number Position   Age Height  Weight  College  \
312  Al Horford  Atlanta Hawks    15.0        C  30.0   6-10   245.0  Florida

         Salary
312  12000000.0

Al Jefferson
             Name               Team  Number Position   Age Height  Weight  \
330  Al Jefferson  Charlotte Hornets    25.0        C  31.0   6-10   289.0

    College      Salary
330     NaN  13500000.0

Al-Farouq Aminu
                Name                    Team  Number Position   Age Height  \
428  Al-Farouq Aminu  Portland Trail Blazers     8.0       SF  25.0    6-9

     Weight      College     Salary
428   215.0  Wake Forest  8042895.0

Alan Anderson
              Name                Team  Number Position   Age Height  Weight  \
368  Alan Anderson  Washington Wizards     6.0       SG  33.0    6-6   220.0

            College     Salary
368  Michigan State  4000000.0

Alan Williams
              Name          Team  Number Position   Age Height  Weight  \
135  Alan Williams  Phoenix Suns    15.0        C  23.0    6-8   260.0

              College   Salary
135  UC Santa Barbara  83397.0

Alec Burks
           Name       Team  Number Position   Age Height  Weight   College  \
444  Alec Burks  Utah Jazz    10.0       SG  24.0    6-6   214.0  Colorado

        Salary
444  9463484.0

Alex Len
         Name          Team  Number Position   Age Height  Weight   College  \
128  Alex Len  Phoenix Suns    21.0        C  22.0    7-1   260.0  Maryland

        Salary
128  3807120.0

Alex Stepheson
               Name               Team  Number Position   Age Height  Weight  \
273  Alex Stepheson  Memphis Grizzlies    35.0       PF  28.0   6-10   270.0

    College  Salary
273     USC     NaN

Alexis Ajinca
              Name                  Team  Number Position   Age Height  \
275  Alexis Ajinca  New Orleans Pelicans    42.0        C  28.0    7-2

     Weight College     Salary
275   248.0     NaN  4389607.0

Allen Crabbe
             Name                    Team  Number Position   Age Height  \
430  Allen Crabbe  Portland Trail Blazers    23.0       SG  24.0    6-6

     Weight     College    Salary
430   210.0  California  947276.0

Alonzo Gee
           Name                  Team  Number Position   Age Height  Weight  \
287  Alonzo Gee  New Orleans Pelicans    15.0       SF  29.0    6-6   225.0

     College     Salary
287  Alabama  1320000.0

Amar'e Stoudemire
                  Name        Team  Number Position   Age Height  Weight  \
348  Amar'e Stoudemire  Miami Heat     5.0       PF  33.0   6-10   245.0

    College    Salary
348     NaN  947276.0

Amir Johnson
           Name            Team  Number Position   Age Height  Weight College  \
5  Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0     NaN

       Salary
5  12000000.0

Anderson Varejao
                Name                   Team  Number Position   Age Height  \
90  Anderson Varejao  Golden State Warriors    18.0       PF  33.0   6-11

    Weight College    Salary
90   273.0     NaN  289755.0

Andre Drummond
               Name             Team  Number Position   Age Height  Weight  \
188  Andre Drummond  Detroit Pistons     0.0        C  22.0   6-11   279.0

         College     Salary
188  Connecticut  3272091.0

Andre Iguodala
              Name                   Team  Number Position   Age Height  \
83  Andre Iguodala  Golden State Warriors     9.0       SF  32.0    6-6

    Weight  College      Salary
83   215.0  Arizona  11710456.0

Andre Miller
             Name               Team  Number Position   Age Height  Weight  \
304  Andre Miller  San Antonio Spurs    24.0       PG  40.0    6-3   200.0

    College    Salary
304    Utah  250750.0

Andre Roberson
               Name                   Team  Number Position   Age Height  \
423  Andre Roberson  Oklahoma City Thunder    21.0       SG  24.0    6-7

     Weight   College     Salary
423   210.0  Colorado  1210800.0

Andrew Bogut
            Name                   Team  Number Position   Age Height  Weight  \
78  Andrew Bogut  Golden State Warriors    12.0        C  31.0    7-0   260.0

   College      Salary
78    Utah  13800000.0

Andrew Goudelock
                 Name             Team  Number Position   Age Height  Weight  \
248  Andrew Goudelock  Houston Rockets     0.0       PG  27.0    6-3   200.0

        College    Salary
248  Charleston  200600.0

Andrew Nicholson
                 Name           Team  Number Position   Age Height  Weight  \
362  Andrew Nicholson  Orlando Magic    44.0       PF  26.0    6-9   250.0

             College     Salary
362  St. Bonaventure  2380593.0

Andrew Wiggins
               Name                    Team  Number Position   Age Height  \
411  Andrew Wiggins  Minnesota Timberwolves    22.0       SG  21.0    6-8

     Weight College     Salary
411   199.0  Kansas  5758680.0

Anthony Brown
              Name                Team  Number Position   Age Height  Weight  \
108  Anthony Brown  Los Angeles Lakers     3.0       SF  23.0    6-7   210.0

      College    Salary
108  Stanford  700000.0

Anthony Davis
              Name                  Team  Number Position   Age Height  \
281  Anthony Davis  New Orleans Pelicans    23.0       PF  23.0   6-10

     Weight   College     Salary
281   253.0  Kentucky  7070730.0

Anthony Morrow
               Name                   Team  Number Position   Age Height  \
421  Anthony Morrow  Oklahoma City Thunder     2.0       SG  30.0    6-5

     Weight       College     Salary
421   210.0  Georgia Tech  3344000.0

Anthony Tolliver
                 Name             Team  Number Position   Age Height  Weight  \
195  Anthony Tolliver  Detroit Pistons    43.0       PF  31.0    6-8   240.0

       College     Salary
195  Creighton  3000000.0

Archie Goodwin
               Name          Team  Number Position   Age Height  Weight  \
125  Archie Goodwin  Phoenix Suns    20.0       SG  21.0    6-5   200.0

      College     Salary
125  Kentucky  1160160.0

Aron Baynes
            Name             Team  Number Position   Age Height  Weight  \
182  Aron Baynes  Detroit Pistons    12.0        C  29.0   6-10   260.0

              College     Salary
182  Washington State  6500000.0

Arron Afflalo
             Name             Team  Number Position   Age Height  Weight  \
30  Arron Afflalo  New York Knicks     4.0       SG  30.0    6-5   210.0

   College     Salary
30    UCLA  8000000.0

Austin Rivers
              Name                  Team  Number Position   Age Height  \
104  Austin Rivers  Los Angeles Clippers    25.0       PG  23.0    6-4

     Weight College     Salary
104   200.0    Duke  3110796.0

Avery Bradley
            Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0

  College     Salary
0   Texas  7730337.0

Axel Toupane
             Name            Team  Number Position   Age Height  Weight  \
397  Axel Toupane  Denver Nuggets     6.0       SG  23.0    6-7   210.0

    College  Salary
397     NaN     NaN

Ben McLemore
             Name              Team  Number Position   Age Height  Weight  \
148  Ben McLemore  Sacramento Kings    23.0       SG  23.0    6-5   195.0

    College     Salary
148  Kansas  3156600.0

Bismack Biyombo
               Name             Team  Number Position   Age Height  Weight  \
61  Bismack Biyombo  Toronto Raptors     8.0        C  23.0    6-9   245.0

   College     Salary
61     NaN  2814000.0

Blake Griffin
             Name                  Team  Number Position   Age Height  Weight  \
96  Blake Griffin  Los Angeles Clippers    32.0       PF  27.0   6-10   251.0

     College      Salary
96  Oklahoma  18907726.0

Boban Marjanovic
                 Name               Team  Number Position   Age Height  \
302  Boban Marjanovic  San Antonio Spurs    40.0        C  27.0    7-3

     Weight College     Salary
302   290.0     NaN  1200000.0

Bobby Portis
             Name           Team  Number Position   Age Height  Weight  \
163  Bobby Portis  Chicago Bulls     5.0       PF  21.0   6-11   230.0

      College     Salary
163  Arkansas  1391160.0

Bojan Bogdanovic
                Name           Team  Number Position   Age Height  Weight  \
15  Bojan Bogdanovic  Brooklyn Nets    44.0       SG  27.0    6-8   216.0

   College     Salary
15     NaN  3425510.0

Boris Diaw
           Name               Team  Number Position   Age Height  Weight  \
297  Boris Diaw  San Antonio Spurs    33.0        C  34.0    6-8   250.0

    College     Salary
297     NaN  7500000.0

Bradley Beal
             Name                Team  Number Position   Age Height  Weight  \
369  Bradley Beal  Washington Wizards     3.0       SG  22.0    6-5   207.0

     College     Salary
369  Florida  5694674.0

Brandan Wright
               Name               Team  Number Position   Age Height  Weight  \
274  Brandan Wright  Memphis Grizzlies    34.0       PF  28.0   6-10   210.0

            College     Salary
274  North Carolina  5464000.0

Branden Dawson
              Name                  Team  Number Position   Age Height  \
94  Branden Dawson  Los Angeles Clippers    22.0       SF  23.0    6-6

    Weight         College    Salary
94   225.0  Michigan State  525093.0

Brandon Bass
             Name                Team  Number Position   Age Height  Weight  \
106  Brandon Bass  Los Angeles Lakers     2.0       PF  31.0    6-8   250.0

    College     Salary
106     LSU  3000000.0

Brandon Jennings
                 Name           Team  Number Position   Age Height  Weight  \
359  Brandon Jennings  Orlando Magic    55.0       PG  26.0    6-1   169.0

    College     Salary
359     NaN  8344497.0

Brandon Knight
               Name          Team  Number Position   Age Height  Weight  \
127  Brandon Knight  Phoenix Suns     3.0       PG  24.0    6-3   189.0

      College      Salary
127  Kentucky  13500000.0

Brandon Rush
            Name                   Team  Number Position   Age Height  Weight  \
87  Brandon Rush  Golden State Warriors     4.0       SF  30.0    6-6   220.0

   College     Salary
87  Kansas  1270964.0

Brian Roberts
              Name                    Team  Number Position   Age Height  \
440  Brian Roberts  Portland Trail Blazers     2.0       PG  30.0    6-1

     Weight College     Salary
440   173.0  Dayton  2854940.0

Briante Weber
              Name        Team  Number Position   Age Height  Weight  \
350  Briante Weber  Miami Heat    12.0       PG  23.0    6-2   165.0

                   College  Salary
350  Virginia Commonwealth     NaN

Brook Lopez
           Name           Team  Number Position   Age Height  Weight  \
23  Brook Lopez  Brooklyn Nets    11.0        C  28.0    7-0   275.0

     College      Salary
23  Stanford  19689000.0

Bruno Caboclo
             Name             Team  Number Position   Age Height  Weight  \
62  Bruno Caboclo  Toronto Raptors    20.0       SF  20.0    6-9   205.0

   College     Salary
62     NaN  1524000.0

Bryce Cotton
             Name               Team  Number Position   Age Height  Weight  \
263  Bryce Cotton  Memphis Grizzlies     8.0       PG  23.0    6-1   165.0

        College    Salary
263  Providence  700902.0

Bryce Dejean-Jones
                   Name                  Team  Number Position   Age Height  \
282  Bryce Dejean-Jones  New Orleans Pelicans    31.0       SG  23.0    6-6

     Weight     College    Salary
282   203.0  Iowa State  169883.0

C.J. McCollum
              Name                    Team  Number Position   Age Height  \
437  C.J. McCollum  Portland Trail Blazers     3.0       SG  24.0    6-4

     Weight College     Salary
437   200.0  Lehigh  2525160.0

C.J. Miles
           Name            Team  Number Position   Age Height  Weight College  \
205  C.J. Miles  Indiana Pacers     0.0       SF  29.0    6-6   231.0     NaN

        Salary
205  4394225.0

C.J. Watson
            Name           Team  Number Position   Age Height  Weight  \
367  C.J. Watson  Orlando Magic    32.0       PG  32.0    6-2   175.0

       College     Salary
367  Tennessee  5000000.0

C.J. Wilcox
            Name                  Team  Number Position   Age Height  Weight  \
105  C.J. Wilcox  Los Angeles Clippers    30.0       SG  25.0    6-5   195.0

        College     Salary
105  Washington  1159680.0

Cameron Bairstow
                 Name           Team  Number Position   Age Height  Weight  \
151  Cameron Bairstow  Chicago Bulls    41.0       PF  25.0    6-9   250.0

        College    Salary
151  New Mexico  845059.0

Cameron Payne
              Name                   Team  Number Position   Age Height  \
422  Cameron Payne  Oklahoma City Thunder    22.0       PG  21.0    6-3

     Weight       College     Salary
422   185.0  Murray State  2021520.0

Carl Landry
           Name                Team  Number Position   Age Height  Weight  \
52  Carl Landry  Philadelphia 76ers     7.0       PF  32.0    6-9   248.0

   College     Salary
52  Purdue  6500000.0

Carmelo Anthony
               Name             Team  Number Position   Age Height  Weight  \
33  Carmelo Anthony  New York Knicks     7.0       SF  32.0    6-8   240.0

     College      Salary
33  Syracuse  22875000.0

Caron Butler
             Name              Team  Number Position   Age Height  Weight  \
139  Caron Butler  Sacramento Kings    31.0       SF  36.0    6-7   228.0

         College     Salary
139  Connecticut  1449187.0

Chandler Parsons
                 Name              Team  Number Position   Age Height  Weight  \
238  Chandler Parsons  Dallas Mavericks    25.0       SF  27.0   6-10   230.0

     College      Salary
238  Florida  15361500.0

Channing Frye
              Name                 Team  Number Position   Age Height  Weight  \
167  Channing Frye  Cleveland Cavaliers     9.0       PF  33.0   6-11   255.0

     College     Salary
167  Arizona  8193029.0

Charlie Villanueva
                   Name              Team  Number Position   Age Height  \
240  Charlie Villanueva  Dallas Mavericks     3.0       PF  31.0   6-11

     Weight      College    Salary
240   232.0  Connecticut  947276.0

Chase Budinger
               Name          Team  Number Position   Age Height  Weight  \
123  Chase Budinger  Phoenix Suns    10.0       SF  28.0    6-7   209.0

     College    Salary
123  Arizona  206192.0

Chris Andersen
               Name               Team  Number Position   Age Height  Weight  \
259  Chris Andersen  Memphis Grizzlies     7.0       PF  37.0   6-10   245.0

           College     Salary
259  Blinn College  5000000.0

Chris Bosh
           Name        Team  Number Position   Age Height  Weight  \
339  Chris Bosh  Miami Heat     1.0       PF  32.0   6-11   235.0

          College      Salary
339  Georgia Tech  22192730.0

Chris Johnson
              Name       Team  Number Position   Age Height  Weight College  \
451  Chris Johnson  Utah Jazz    23.0       SF  26.0    6-6   206.0  Dayton

       Salary
451  981348.0

Chris Kaman
            Name                    Team  Number Position   Age Height  \
434  Chris Kaman  Portland Trail Blazers    35.0        C  34.0    7-0

     Weight           College     Salary
434   265.0  Central Michigan  5016000.0

Chris McCullough
                Name           Team  Number Position   Age Height  Weight  \
24  Chris McCullough  Brooklyn Nets     1.0       PF  21.0   6-11   200.0

     College     Salary
24  Syracuse  1140240.0

Chris Paul
           Name                  Team  Number Position   Age Height  Weight  \
100  Chris Paul  Los Angeles Clippers     3.0       PG  31.0    6-0   175.0

         College      Salary
100  Wake Forest  21468695.0

Christian Wood
              Name                Team  Number Position   Age Height  Weight  \
60  Christian Wood  Philadelphia 76ers    35.0       PF  20.0   6-11   220.0

   College    Salary
60    UNLV  525093.0

Cleanthony Early
                Name             Team  Number Position   Age Height  Weight  \
35  Cleanthony Early  New York Knicks    11.0       SF  25.0    6-8   210.0

          College    Salary
35  Wichita State  845059.0

Cliff Alexander
                Name                    Team  Number Position   Age Height  \
427  Cliff Alexander  Portland Trail Blazers    34.0       PF  20.0    6-8

     Weight College    Salary
427   240.0  Kansas  525093.0

Clint Capela
             Name             Team  Number Position   Age Height  Weight  \
246  Clint Capela  Houston Rockets    15.0       PF  22.0   6-10   240.0

    College     Salary
246     NaN  1242720.0

Cody Zeller
            Name               Team  Number Position   Age Height  Weight  \
338  Cody Zeller  Charlotte Hornets    40.0        C  23.0    7-0   240.0

     College     Salary
338  Indiana  4204200.0

Cole Aldrich
            Name                  Team  Number Position   Age Height  Weight  \
91  Cole Aldrich  Los Angeles Clippers    45.0        C  27.0   6-11   250.0

   College     Salary
91  Kansas  1100602.0

Corey Brewer
             Name             Team  Number Position   Age Height  Weight  \
245  Corey Brewer  Houston Rockets    33.0       SG  30.0    6-9   186.0

     College     Salary
245  Florida  8229375.0

Cory Joseph
           Name             Team  Number Position   Age Height  Weight  \
66  Cory Joseph  Toronto Raptors     6.0       PG  24.0    6-3   190.0

   College     Salary
66   Texas  7000000.0

Courtney Lee
             Name               Team  Number Position   Age Height  Weight  \
334  Courtney Lee  Charlotte Hornets     1.0       SG  30.0    6-5   200.0

              College     Salary
334  Western Kentucky  5675000.0

Cristiano Felicio
                  Name           Team  Number Position   Age Height  Weight  \
155  Cristiano Felicio  Chicago Bulls     6.0       PF  23.0   6-10   275.0

    College    Salary
155     NaN  525093.0

D'Angelo Russell
                 Name                Team  Number Position   Age Height  \
116  D'Angelo Russell  Los Angeles Lakers     1.0       PG  20.0    6-5

     Weight     College     Salary
116   195.0  Ohio State  5103120.0

D.J. Augustin
              Name            Team  Number Position   Age Height  Weight  \
384  D.J. Augustin  Denver Nuggets    12.0       PG  28.0    6-0   183.0

    College     Salary
384   Texas  3000000.0

Dahntay Jones
              Name                 Team  Number Position   Age Height  Weight  \
171  Dahntay Jones  Cleveland Cavaliers    30.0       SG  35.0    6-6   225.0

    College  Salary
171    Duke     NaN

Damian Lillard
               Name                    Team  Number Position   Age Height  \
436  Damian Lillard  Portland Trail Blazers     0.0       PG  25.0    6-3

     Weight      College     Salary
436   195.0  Weber State  4236287.0

Damien Inglis
              Name             Team  Number Position   Age Height  Weight  \
217  Damien Inglis  Milwaukee Bucks    17.0       SF  21.0    6-8   246.0

    College    Salary
217     NaN  855000.0

Damjan Rudez
             Name                    Team  Number Position   Age Height  \
408  Damjan Rudez  Minnesota Timberwolves    10.0       SF  29.0    6-9


In [59]:
grp = df_csv.groupby(['Name', 'Age'])
for name, group in grp:
    print(name)
    print(group)
    print()

('Aaron Brooks', 31.0)
             Name           Team  Number Position   Age Height  Weight  \
152  Aaron Brooks  Chicago Bulls     0.0       PG  31.0    6-0   161.0

    College     Salary
152  Oregon  2250000.0

('Aaron Gordon', 20.0)
             Name           Team  Number Position   Age Height  Weight  \
356  Aaron Gordon  Orlando Magic     0.0       PF  20.0    6-9   220.0

     College     Salary
356  Arizona  4171680.0

('Aaron Harrison', 21.0)
               Name               Team  Number Position   Age Height  Weight  \
328  Aaron Harrison  Charlotte Hornets     9.0       SG  21.0    6-6   210.0

      College    Salary
328  Kentucky  525093.0

('Adreian Payne', 25.0)
              Name                    Team  Number Position   Age Height  \
404  Adreian Payne  Minnesota Timberwolves    33.0       PF  25.0   6-10

     Weight         College     Salary
404   237.0  Michigan State  1938840.0

('Al Horford', 30.0)
           Name           Team  Number Position   Age Height  Weight  College  \
312  Al Horford  Atlanta Hawks    15.0        C  30.0   6-10   245.0  Florida

         Salary
312  12000000.0

('Al Jefferson', 31.0)
             Name               Team  Number Position   Age Height  Weight  \
330  Al Jefferson  Charlotte Hornets    25.0        C  31.0   6-10   289.0

    College      Salary
330     NaN  13500000.0

('Al-Farouq Aminu', 25.0)
                Name                    Team  Number Position   Age Height  \
428  Al-Farouq Aminu  Portland Trail Blazers     8.0       SF  25.0    6-9

     Weight      College     Salary
428   215.0  Wake Forest  8042895.0

('Alan Anderson', 33.0)
              Name                Team  Number Position   Age Height  Weight  \
368  Alan Anderson  Washington Wizards     6.0       SG  33.0    6-6   220.0

            College     Salary
368  Michigan State  4000000.0

('Alan Williams', 23.0)
              Name          Team  Number Position   Age Height  Weight  \
135  Alan Williams  Phoenix Suns    15.0        C  23.0    6-8   260.0

              College   Salary
135  UC Santa Barbara  83397.0

('Alec Burks', 24.0)
           Name       Team  Number Position   Age Height  Weight   College  \
444  Alec Burks  Utah Jazz    10.0       SG  24.0    6-6   214.0  Colorado

        Salary
444  9463484.0

('Alex Len', 22.0)
         Name          Team  Number Position   Age Height  Weight   College  \
128  Alex Len  Phoenix Suns    21.0        C  22.0    7-1   260.0  Maryland

        Salary
128  3807120.0

('Alex Stepheson', 28.0)
               Name               Team  Number Position   Age Height  Weight  \
273  Alex Stepheson  Memphis Grizzlies    35.0       PF  28.0   6-10   270.0

    College  Salary
273     USC     NaN

('Alexis Ajinca', 28.0)
              Name                  Team  Number Position   Age Height  \
275  Alexis Ajinca  New Orleans Pelicans    42.0        C  28.0    7-2

     Weight College     Salary
275   248.0     NaN  4389607.0

('Allen Crabbe', 24.0)
             Name                    Team  Number Position   Age Height  \
430  Allen Crabbe  Portland Trail Blazers    23.0       SG  24.0    6-6

     Weight     College    Salary
430   210.0  California  947276.0

('Alonzo Gee', 29.0)
           Name                  Team  Number Position   Age Height  Weight  \
287  Alonzo Gee  New Orleans Pelicans    15.0       SF  29.0    6-6   225.0

     College     Salary
287  Alabama  1320000.0

("Amar'e Stoudemire", 33.0)
                  Name        Team  Number Position   Age Height  Weight  \
348  Amar'e Stoudemire  Miami Heat     5.0       PF  33.0   6-10   245.0

    College    Salary
348     NaN  947276.0

('Amir Johnson', 29.0)
           Name            Team  Number Position   Age Height  Weight College  \
5  Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0     NaN

       Salary
5  12000000.0

('Anderson Varejao', 33.0)
                Name                   Team  Number Position   Age Height  \
90  Anderson Varejao  Golden State Warriors    18.0       PF  33.0   6-11

    Weight College    Salary
90   273.0     NaN  289755.0

('Andre Drummond', 22.0)
               Name             Team  Number Position   Age Height  Weight  \
188  Andre Drummond  Detroit Pistons     0.0        C  22.0   6-11   279.0

         College     Salary
188  Connecticut  3272091.0

('Andre Iguodala', 32.0)
              Name                   Team  Number Position   Age Height  \
83  Andre Iguodala  Golden State Warriors     9.0       SF  32.0    6-6

    Weight  College      Salary
83   215.0  Arizona  11710456.0

('Andre Miller', 40.0)
             Name               Team  Number Position   Age Height  Weight  \
304  Andre Miller  San Antonio Spurs    24.0       PG  40.0    6-3   200.0

    College    Salary
304    Utah  250750.0

('Andre Roberson', 24.0)
               Name                   Team  Number Position   Age Height  \
423  Andre Roberson  Oklahoma City Thunder    21.0       SG  24.0    6-7

     Weight   College     Salary
423   210.0  Colorado  1210800.0

('Andrew Bogut', 31.0)
            Name                   Team  Number Position   Age Height  Weight  \
78  Andrew Bogut  Golden State Warriors    12.0        C  31.0    7-0   260.0

   College      Salary
78    Utah  13800000.0

('Andrew Goudelock', 27.0)
                 Name             Team  Number Position   Age Height  Weight  \
248  Andrew Goudelock  Houston Rockets     0.0       PG  27.0    6-3   200.0

        College    Salary
248  Charleston  200600.0

('Andrew Nicholson', 26.0)
                 Name           Team  Number Position   Age Height  Weight  \
362  Andrew Nicholson  Orlando Magic    44.0       PF  26.0    6-9   250.0

             College     Salary
362  St. Bonaventure  2380593.0

('Andrew Wiggins', 21.0)
               Name                    Team  Number Position   Age Height  \
411  Andrew Wiggins  Minnesota Timberwolves    22.0       SG  21.0    6-8

     Weight College     Salary
411   199.0  Kansas  5758680.0

('Anthony Brown', 23.0)
              Name                Team  Number Position   Age Height  Weight  \
108  Anthony Brown  Los Angeles Lakers     3.0       SF  23.0    6-7   210.0

      College    Salary
108  Stanford  700000.0

('Anthony Davis', 23.0)
              Name                  Team  Number Position   Age Height  \
281  Anthony Davis  New Orleans Pelicans    23.0       PF  23.0   6-10

     Weight   College     Salary
281   253.0  Kentucky  7070730.0

('Anthony Morrow', 30.0)
               Name                   Team  Number Position   Age Height  \
421  Anthony Morrow  Oklahoma City Thunder     2.0       SG  30.0    6-5

     Weight       College     Salary
421   210.0  Georgia Tech  3344000.0

('Anthony Tolliver', 31.0)
                 Name             Team  Number Position   Age Height  Weight  \
195  Anthony Tolliver  Detroit Pistons    43.0       PF  31.0    6-8   240.0

       College     Salary
195  Creighton  3000000.0

('Archie Goodwin', 21.0)
               Name          Team  Number Position   Age Height  Weight  \
125  Archie Goodwin  Phoenix Suns    20.0       SG  21.0    6-5   200.0

      College     Salary
125  Kentucky  1160160.0

('Aron Baynes', 29.0)
            Name             Team  Number Position   Age Height  Weight  \
182  Aron Baynes  Detroit Pistons    12.0        C  29.0   6-10   260.0

              College     Salary
182  Washington State  6500000.0

('Arron Afflalo', 30.0)
             Name             Team  Number Position   Age Height  Weight  \
30  Arron Afflalo  New York Knicks     4.0       SG  30.0    6-5   210.0

   College     Salary
30    UCLA  8000000.0

('Austin Rivers', 23.0)
              Name                  Team  Number Position   Age Height  \
104  Austin Rivers  Los Angeles Clippers    25.0       PG  23.0    6-4

     Weight College     Salary
104   200.0    Duke  3110796.0

('Avery Bradley', 25.0)
            Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0

  College     Salary
0   Texas  7730337.0

('Axel Toupane', 23.0)
             Name            Team  Number Position   Age Height  Weight  \
397  Axel Toupane  Denver Nuggets     6.0       SG  23.0    6-7   210.0

    College  Salary
397     NaN     NaN

('Ben McLemore', 23.0)
             Name              Team  Number Position   Age Height  Weight  \
148  Ben McLemore  Sacramento Kings    23.0       SG  23.0    6-5   195.0

    College     Salary
148  Kansas  3156600.0

('Bismack Biyombo', 23.0)
               Name             Team  Number Position   Age Height  Weight  \
61  Bismack Biyombo  Toronto Raptors     8.0        C  23.0    6-9   245.0

   College     Salary
61     NaN  2814000.0

('Blake Griffin', 27.0)
             Name                  Team  Number Position   Age Height  Weight  \
96  Blake Griffin  Los Angeles Clippers    32.0       PF  27.0   6-10   251.0

     College      Salary
96  Oklahoma  18907726.0

('Boban Marjanovic', 27.0)
                 Name               Team  Number Position   Age Height  \
302  Boban Marjanovic  San Antonio Spurs    40.0        C  27.0    7-3

     Weight College     Salary
302   290.0     NaN  1200000.0

('Bobby Portis', 21.0)
             Name           Team  Number Position   Age Height  Weight  \
163  Bobby Portis  Chicago Bulls     5.0       PF  21.0   6-11   230.0

      College     Salary
163  Arkansas  1391160.0

('Bojan Bogdanovic', 27.0)
                Name           Team  Number Position   Age Height  Weight  \
15  Bojan Bogdanovic  Brooklyn Nets    44.0       SG  27.0    6-8   216.0

   College     Salary
15     NaN  3425510.0

('Boris Diaw', 34.0)
           Name               Team  Number Position   Age Height  Weight  \
297  Boris Diaw  San Antonio Spurs    33.0        C  34.0    6-8   250.0

    College     Salary
297     NaN  7500000.0

('Bradley Beal', 22.0)
             Name                Team  Number Position   Age Height  Weight  \
369  Bradley Beal  Washington Wizards     3.0       SG  22.0    6-5   207.0

     College     Salary
369  Florida  5694674.0

('Brandan Wright', 28.0)
               Name               Team  Number Position   Age Height  Weight  \
274  Brandan Wright  Memphis Grizzlies    34.0       PF  28.0   6-10   210.0

            College     Salary
274  North Carolina  5464000.0

('Branden Dawson', 23.0)
              Name                  Team  Number Position   Age Height  \
94  Branden Dawson  Los Angeles Clippers    22.0       SF  23.0    6-6

    Weight         College    Salary
94   225.0  Michigan State  525093.0

('Brandon Bass', 31.0)
             Name                Team  Number Position   Age Height  Weight  \
106  Brandon Bass  Los Angeles Lakers     2.0       PF  31.0    6-8   250.0

    College     Salary
106     LSU  3000000.0

('Brandon Jennings', 26.0)
                 Name           Team  Number Position   Age Height  Weight  \
359  Brandon Jennings  Orlando Magic    55.0       PG  26.0    6-1   169.0

    College     Salary
359     NaN  8344497.0

('Brandon Knight', 24.0)
               Name          Team  Number Position   Age Height  Weight  \
127  Brandon Knight  Phoenix Suns     3.0       PG  24.0    6-3   189.0

      College      Salary
127  Kentucky  13500000.0

('Brandon Rush', 30.0)
            Name                   Team  Number Position   Age Height  Weight  \
87  Brandon Rush  Golden State Warriors     4.0       SF  30.0    6-6   220.0

   College     Salary
87  Kansas  1270964.0

('Brian Roberts', 30.0)
              Name                    Team  Number Position   Age Height  \
440  Brian Roberts  Portland Trail Blazers     2.0       PG  30.0    6-1

     Weight College     Salary
440   173.0  Dayton  2854940.0

('Briante Weber', 23.0)
              Name        Team  Number Position   Age Height  Weight  \
350  Briante Weber  Miami Heat    12.0       PG  23.0    6-2   165.0

                   College  Salary
350  Virginia Commonwealth     NaN

('Brook Lopez', 28.0)
           Name           Team  Number Position   Age Height  Weight  \
23  Brook Lopez  Brooklyn Nets    11.0        C  28.0    7-0   275.0

     College      Salary
23  Stanford  19689000.0

('Bruno Caboclo', 20.0)
             Name             Team  Number Position   Age Height  Weight  \
62  Bruno Caboclo  Toronto Raptors    20.0       SF  20.0    6-9   205.0

   College     Salary
62     NaN  1524000.0

('Bryce Cotton', 23.0)
             Name               Team  Number Position   Age Height  Weight  \
263  Bryce Cotton  Memphis Grizzlies     8.0       PG  23.0    6-1   165.0

        College    Salary
263  Providence  700902.0

('Bryce Dejean-Jones', 23.0)
                   Name                  Team  Number Position   Age Height  \
282  Bryce Dejean-Jones  New Orleans Pelicans    31.0       SG  23.0    6-6

     Weight     College    Salary
282   203.0  Iowa State  169883.0

('C.J. McCollum', 24.0)
              Name                    Team  Number Position   Age Height  \
437  C.J. McCollum  Portland Trail Blazers     3.0       SG  24.0    6-4

     Weight College     Salary
437   200.0  Lehigh  2525160.0

('C.J. Miles', 29.0)
           Name            Team  Number Position   Age Height  Weight College  \
205  C.J. Miles  Indiana Pacers     0.0       SF  29.0    6-6   231.0     NaN

        Salary
205  4394225.0

('C.J. Watson', 32.0)
            Name           Team  Number Position   Age Height  Weight  \
367  C.J. Watson  Orlando Magic    32.0       PG  32.0    6-2   175.0

       College     Salary
367  Tennessee  5000000.0

('C.J. Wilcox', 25.0)
            Name                  Team  Number Position   Age Height  Weight  \
105  C.J. Wilcox  Los Angeles Clippers    30.0       SG  25.0    6-5   195.0

        College     Salary
105  Washington  1159680.0

('Cameron Bairstow', 25.0)
                 Name           Team  Number Position   Age Height  Weight  \
151  Cameron Bairstow  Chicago Bulls    41.0       PF  25.0    6-9   250.0

        College    Salary
151  New Mexico  845059.0

('Cameron Payne', 21.0)
              Name                   Team  Number Position   Age Height  \
422  Cameron Payne  Oklahoma City Thunder    22.0       PG  21.0    6-3

     Weight       College     Salary
422   185.0  Murray State  2021520.0

('Carl Landry', 32.0)
           Name                Team  Number Position   Age Height  Weight  \
52  Carl Landry  Philadelphia 76ers     7.0       PF  32.0    6-9   248.0

   College     Salary
52  Purdue  6500000.0

('Carmelo Anthony', 32.0)
               Name             Team  Number Position   Age Height  Weight  \
33  Carmelo Anthony  New York Knicks     7.0       SF  32.0    6-8   240.0

     College      Salary
33  Syracuse  22875000.0

('Caron Butler', 36.0)
             Name              Team  Number Position   Age Height  Weight  \
139  Caron Butler  Sacramento Kings    31.0       SF  36.0    6-7   228.0

         College     Salary
139  Connecticut  1449187.0

('Chandler Parsons', 27.0)
                 Name              Team  Number Position   Age Height  Weight  \
238  Chandler Parsons  Dallas Mavericks    25.0       SF  27.0   6-10   230.0

     College      Salary
238  Florida  15361500.0

('Channing Frye', 33.0)
              Name                 Team  Number Position   Age Height  Weight  \
167  Channing Frye  Cleveland Cavaliers     9.0       PF  33.0   6-11   255.0

     College     Salary
167  Arizona  8193029.0

('Charlie Villanueva', 31.0)
                   Name              Team  Number Position   Age Height  \
240  Charlie Villanueva  Dallas Mavericks     3.0       PF  31.0   6-11

     Weight      College    Salary
240   232.0  Connecticut  947276.0

('Chase Budinger', 28.0)
               Name          Team  Number Position   Age Height  Weight  \
123  Chase Budinger  Phoenix Suns    10.0       SF  28.0    6-7   209.0

     College    Salary
123  Arizona  206192.0

('Chris Andersen', 37.0)
               Name               Team  Number Position   Age Height  Weight  \
259  Chris Andersen  Memphis Grizzlies     7.0       PF  37.0   6-10   245.0

           College     Salary
259  Blinn College  5000000.0

('Chris Bosh', 32.0)
           Name        Team  Number Position   Age Height  Weight  \
339  Chris Bosh  Miami Heat     1.0       PF  32.0   6-11   235.0

          College      Salary
339  Georgia Tech  22192730.0

('Chris Johnson', 26.0)
              Name       Team  Number Position   Age Height  Weight College  \
451  Chris Johnson  Utah Jazz    23.0       SF  26.0    6-6   206.0  Dayton

       Salary
451  981348.0

('Chris Kaman', 34.0)
            Name                    Team  Number Position   Age Height  \
434  Chris Kaman  Portland Trail Blazers    35.0        C  34.0    7-0

     Weight           College     Salary
434   265.0  Central Michigan  5016000.0

('Chris McCullough', 21.0)
                Name           Team  Number Position   Age Height  Weight  \
24  Chris McCullough  Brooklyn Nets     1.0       PF  21.0   6-11   200.0

     College     Salary
24  Syracuse  1140240.0

('Chris Paul', 31.0)
           Name                  Team  Number Position   Age Height  Weight  \
100  Chris Paul  Los Angeles Clippers     3.0       PG  31.0    6-0   175.0

         College      Salary
100  Wake Forest  21468695.0

('Christian Wood', 20.0)
              Name                Team  Number Position   Age Height  Weight  \
60  Christian Wood  Philadelphia 76ers    35.0       PF  20.0   6-11   220.0

   College    Salary
60    UNLV  525093.0

('Cleanthony Early', 25.0)
                Name             Team  Number Position   Age Height  Weight  \
35  Cleanthony Early  New York Knicks    11.0       SF  25.0    6-8   210.0

          College    Salary
35  Wichita State  845059.0

('Cliff Alexander', 20.0)
                Name                    Team  Number Position   Age Height  \
427  Cliff Alexander  Portland Trail Blazers    34.0       PF  20.0    6-8

     Weight College    Salary
427   240.0  Kansas  525093.0

('Clint Capela', 22.0)
             Name             Team  Number Position   Age Height  Weight  \
246  Clint Capela  Houston Rockets    15.0       PF  22.0   6-10   240.0

    College     Salary
246     NaN  1242720.0

('Cody Zeller', 23.0)
            Name               Team  Number Position   Age Height  Weight  \
338  Cody Zeller  Charlotte Hornets    40.0        C  23.0    7-0   240.0

     College     Salary
338  Indiana  4204200.0

('Cole Aldrich', 27.0)
            Name                  Team  Number Position   Age Height  Weight  \
91  Cole Aldrich  Los Angeles Clippers    45.0        C  27.0   6-11   250.0

   College     Salary
91  Kansas  1100602.0

('Corey Brewer', 30.0)
             Name             Team  Number Position   Age Height  Weight  \
245  Corey Brewer  Houston Rockets    33.0       SG  30.0    6-9   186.0

     College     Salary
245  Florida  8229375.0

('Cory Joseph', 24.0)
           Name             Team  Number Position   Age Height  Weight  \
66  Cory Joseph  Toronto Raptors     6.0       PG  24.0    6-3   190.0

   College     Salary
66   Texas  7000000.0

('Courtney Lee', 30.0)
             Name               Team  Number Position   Age Height  Weight  \
334  Courtney Lee  Charlotte Hornets     1.0       SG  30.0    6-5   200.0

              College     Salary
334  Western Kentucky  5675000.0

('Cristiano Felicio', 23.0)
                  Name           Team  Number Position   Age Height  Weight  \
155  Cristiano Felicio  Chicago Bulls     6.0       PF  23.0   6-10   275.0

    College    Salary
155     NaN  525093.0

("D'Angelo Russell", 20.0)
                 Name                Team  Number Position   Age Height  \
116  D'Angelo Russell  Los Angeles Lakers     1.0       PG  20.0    6-5

     Weight     College     Salary
116   195.0  Ohio State  5103120.0

('D.J. Augustin', 28.0)
              Name            Team  Number Position   Age Height  Weight  \
384  D.J. Augustin  Denver Nuggets    12.0       PG  28.0    6-0   183.0


In [73]:
grp = df_csv.groupby(['Name', 'Age'])
grp.get_group(('Aaron Gordon', 20.0))

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
356,Aaron Gordon,Orlando Magic,0.0,PF,20.0,6-9,220.0,Arizona,4171680.0

In [74]:
grp1 = df_csv.groupby('Name')
grp1['Age'].aggregate(np.sum)

Name
Aaron Brooks       31.0
Aaron Gordon       20.0
Aaron Harrison     21.0
Adreian Payne      25.0
Al Horford         30.0
                   ...
Wilson Chandler    29.0
Xavier Munford     24.0
Zach LaVine        21.0
Zach Randolph      34.0
Zaza Pachulia      32.0
Name: Age, Length: 457, dtype: float64